"""Add expected res for funs

Revision ID: f04430af51e2
Revises: 8233dd7ca744
Create Date: 2026-01-19 18:56:12.824385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f04430af51e2'
down_revision: Union[str, Sequence[str], None] = '8233dd7ca744'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('function_results', sa.Column('expected_result', sa.Enum('UNKNOWN', 'EQUAL', 'NON_EQUAL', name='expectedresulttype'), nullable=True))
    op.add_column('function_results', sa.Column('expected_result_changed_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('function_results', 'expected_result_changed_by')
    op.drop_column('function_results', 'expected_result')
    # ### end Alembic commands ###
